# Data Preprocessing Concepts

- Dataset Link:
https://www.kaggle.com/datasets/lakshmi25npathi/imdb-dataset-of-50k-movie-reviews

In [1]:
import pandas as pd
import re

In [2]:
import zipfile

zip_path = "content/IMDB_Dataset.zip"

with zipfile.ZipFile(zip_path, "r") as zip_ref:
    print(zip_ref.namelist())
    zip_ref.extractall("content/")

print("Done!")

['IMDB Dataset.csv']
Done!

In [3]:
import os
print(os.listdir())

['01Introduction.ipynb', 'Text-Preprocessing.ipynb', 'content', '.ipynb_checkpoints']

In [4]:
data_path = "content/IMDB Dataset.csv"
df = pd.read_csv(data_path)
# pd.set_option("display.max_colwidth", None)

In [5]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [6]:
df = df.head(100)

In [7]:
df.shape

(100, 2)

In [8]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

## Lower Case Operation

In [9]:
df['review'][3] #3rd row taking from the column name

"Basically there's a family where a little boy (Jake) thinks there's a zombie in his closet & his parents are fighting all the time.<br /><br />This movie is slower than a soap opera... and suddenly, Jake decides to become Rambo and kill the zombie.<br /><br />OK, first of all when you're going to make a film you must Decide if its a thriller or a drama! As a drama the movie is watchable. Parents are divorcing & arguing like in real life. And then we have Jake with his closet which totally ruins all the film! I expected to see a BOOGEYMAN similar movie, and instead i watched a drama with some meaningless thriller spots.<br /><br />3 out of 10 just for the well playing parents & descent dialogs. As for the shots with Jake: just ignore them."

In [10]:
df['review'] = df['review'].str.lower() ## This is used to make the text lower

In [11]:
df

                                               review sentiment
0   one of the other reviewers has mentioned that ...  positive
1   a wonderful little production. <br /><br />the...  positive
2   i thought this was a wonderful way to spend ti...  positive
3   basically there's a family where a little boy ...  negative
4   petter mattei's "love in the time of money" is...  positive
..                                                ...       ...
95  daniel day-lewis is the most versatile actor a...  positive
96  my guess would be this was originally going to...  negative
97  well, i like to watch bad horror b-movies, cau...  negative
98  this is the worst movie i have ever seen, as w...  negative
99  i have been a mario fan for as long as i can r...  positive

[100 rows x 2 columns]

In [12]:
df['review'][3]

"basically there's a family where a little boy (jake) thinks there's a zombie in his closet & his parents are fighting all the time.<br /><br />this movie is slower than a soap opera... and suddenly, jake decides to become rambo and kill the zombie.<br /><br />ok, first of all when you're going to make a film you must decide if its a thriller or a drama! as a drama the movie is watchable. parents are divorcing & arguing like in real life. and then we have jake with his closet which totally ruins all the film! i expected to see a boogeyman similar movie, and instead i watched a drama with some meaningless thriller spots.<br /><br />3 out of 10 just for the well playing parents & descent dialogs. as for the shots with jake: just ignore them."

In [13]:
df['review'][4]

'petter mattei\'s "love in the time of money" is a visually stunning film to watch. mr. mattei offers us a vivid portrait about human relations. this is a movie that seems to be telling us what money, power and success do to people in the different situations we encounter. <br /><br />this being a variation on the arthur schnitzler\'s play about the same theme, the director transfers the action to the present time new york where all these different characters meet and connect. each one is connected in one way, or another to the next person, but no one seems to know the previous point of contact. stylishly, the film has a sophisticated luxurious look. we are taken to see how these people live and the world they live in their own habitat.<br /><br />the only thing one gets out of all these souls in the picture is the different stages of loneliness each one inhabits. a big city is not exactly the best place in which human relations find sincere fulfillment, as one discerns is the case with most of the people we encounter.<br /><br />the acting is good under mr. mattei\'s direction. steve buscemi, rosario dawson, carol kane, michael imperioli, adrian grenier, and the rest of the talented cast, make these characters come alive.<br /><br />we wish mr. mattei good luck and await anxiously for his next work.'

## Remove Html Tags Operations

In [14]:
import re
def remove_html_tags(text):
    pattern = re.compile('<.*?>')
    return pattern.sub(r'', text)

In [15]:
text = "<html><body><p> Movie 1</p><p> Actor - Aamir Khan</p><p> Click here to <a href='http://google.com'>download</a></p></body></html>"

In [16]:
remove_html_tags(text)

' Movie 1 Actor - Aamir Khan Click here to download'

In [17]:
df['review'] = df['review'].apply(remove_html_tags)

In [18]:
df['review'][5]

'probably my all-time favorite movie, a story of selflessness, sacrifice and dedication to a noble cause, but it\'s not preachy or boring. it just never gets old, despite my having seen it some 15 or more times in the last 25 years. paul lukas\' performance brings tears to my eyes, and bette davis, in one of her very few truly sympathetic roles, is a delight. the kids are, as grandma says, more like "dressed-up midgets" than children, but that only makes them more fun to watch. and the mother\'s slow awakening to what\'s happening in the world and under her own roof is believable and startling. if i had a dozen thumbs, they\'d all be "up" for this movie.'

In [19]:
df['review'][4]

'petter mattei\'s "love in the time of money" is a visually stunning film to watch. mr. mattei offers us a vivid portrait about human relations. this is a movie that seems to be telling us what money, power and success do to people in the different situations we encounter. this being a variation on the arthur schnitzler\'s play about the same theme, the director transfers the action to the present time new york where all these different characters meet and connect. each one is connected in one way, or another to the next person, but no one seems to know the previous point of contact. stylishly, the film has a sophisticated luxurious look. we are taken to see how these people live and the world they live in their own habitat.the only thing one gets out of all these souls in the picture is the different stages of loneliness each one inhabits. a big city is not exactly the best place in which human relations find sincere fulfillment, as one discerns is the case with most of the people we encounter.the acting is good under mr. mattei\'s direction. steve buscemi, rosario dawson, carol kane, michael imperioli, adrian grenier, and the rest of the talented cast, make these characters come alive.we wish mr. mattei good luck and await anxiously for his next work.'

## Remove Url Operation

In [20]:
def remove_url(text):
    pattern = re.compile(r'https?://\S+|www\.\S+')
    return pattern.sub(r'', text)

In [21]:
text1 = 'Check out my youtube https://www.youtube.com/dswithbappy dswithbappy'
text2 = 'Check out my linkedin https://www.linkedin.com/in/boktiarahmed73/'
text3 = 'Google search here www.google.com'
text4 = 'For data click https://www.kaggle.com/'

In [22]:
remove_url(text4)

'For data click '

In [23]:
df['review'] = df['review'].apply(remove_url)

In [24]:
df['review'][4]

'petter mattei\'s "love in the time of money" is a visually stunning film to watch. mr. mattei offers us a vivid portrait about human relations. this is a movie that seems to be telling us what money, power and success do to people in the different situations we encounter. this being a variation on the arthur schnitzler\'s play about the same theme, the director transfers the action to the present time new york where all these different characters meet and connect. each one is connected in one way, or another to the next person, but no one seems to know the previous point of contact. stylishly, the film has a sophisticated luxurious look. we are taken to see how these people live and the world they live in their own habitat.the only thing one gets out of all these souls in the picture is the different stages of loneliness each one inhabits. a big city is not exactly the best place in which human relations find sincere fulfillment, as one discerns is the case with most of the people we encounter.the acting is good under mr. mattei\'s direction. steve buscemi, rosario dawson, carol kane, michael imperioli, adrian grenier, and the rest of the talented cast, make these characters come alive.we wish mr. mattei good luck and await anxiously for his next work.'

## Punctuation Handling Operation

In [25]:
import string,time
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [26]:
exclude = string.punctuation
exclude

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [27]:
def remove_punc(text):
    for char in exclude:  ## linear time complexity to remove the punctuations
        text = text.replace(char,'')
    return text

In [28]:
text = 'string. With. Punctuation?'

In [29]:
start = time.time()  ## Example to remove the punctuations
print(remove_punc(text))
time1 = time.time() - start
print(time1*50000)

string With Punctuation
7.605552673339844

In [30]:
def remove_punc1(text): ## another method to remove the punctuations
    return text.translate(str.maketrans('', '', exclude)) ## Complexity of O(N)

In [31]:
start = time.time()
remove_punc1(text)
time2 = time.time() - start
print(time2*50000)

5.853176116943359

In [32]:
time1/time2

1.2993890020366599

In [33]:
df['review'][5]

'probably my all-time favorite movie, a story of selflessness, sacrifice and dedication to a noble cause, but it\'s not preachy or boring. it just never gets old, despite my having seen it some 15 or more times in the last 25 years. paul lukas\' performance brings tears to my eyes, and bette davis, in one of her very few truly sympathetic roles, is a delight. the kids are, as grandma says, more like "dressed-up midgets" than children, but that only makes them more fun to watch. and the mother\'s slow awakening to what\'s happening in the world and under her own roof is believable and startling. if i had a dozen thumbs, they\'d all be "up" for this movie.'

In [34]:
df['review'] = df['review'].apply(remove_punc1)

In [35]:
df['review'][3]

'basically theres a family where a little boy jake thinks theres a zombie in his closet  his parents are fighting all the timethis movie is slower than a soap opera and suddenly jake decides to become rambo and kill the zombieok first of all when youre going to make a film you must decide if its a thriller or a drama as a drama the movie is watchable parents are divorcing  arguing like in real life and then we have jake with his closet which totally ruins all the film i expected to see a boogeyman similar movie and instead i watched a drama with some meaningless thriller spots3 out of 10 just for the well playing parents  descent dialogs as for the shots with jake just ignore them'

## Chat Conversion Handle Operations

In [36]:
chat_words = {
    'AFAIK':'As Far As I Know',
    'AFK':'Away From Keyboard',
    'ASAP':'As Soon As Possible',
    "FYI": "For Your Information",
    "ASAP": "As Soon As Possible",
    "BRB": "Be Right Back",
    "BTW": "By The Way",
    "OMG": "Oh My God",
    "IMO": "In My Opinion",
    "LOL": "Laugh Out Loud",
    "TTYL": "Talk To You Later",
    "GTG": "Got To Go",
    "TTYT": "Talk To You Tomorrow",
    "IDK": "I Don't Know",
    "TMI": "Too Much Information",
    "IMHO": "In My Humble Opinion",
    "ICYMI": "In Case You Missed It",
    "AFAIK": "As Far As I Know",
    "BTW": "By The Way",
    "FAQ": "Frequently Asked Questions",
    "TGIF": "Thank God It's Friday",
    "FYA": "For Your Action",
    "ICYMI": "In Case You Missed It",
}

In [37]:
def chat_conversion(text):
    new_text = []
    for w in text.split():
        if w.upper() in chat_words:
            new_text.append(chat_words[w.upper()])
        else:
            new_text.append(w)
    return " ".join(new_text)

In [38]:
chat_conversion('Do this work ASAP')

'Do this work As Soon As Possible'

In [39]:
# 1. Non-capturing pattern (silences warning in .str.contains)
check_pattern = r"\b(?:" + "|".join(map(re.escape, chat_words.keys())) + r")\b"

# 2. Capturing pattern (required for .str.extract)
extract_pattern = (
    r"\b(" + "|".join(map(re.escape, chat_words.keys())) + r")\b"
)

# 3. Filter rows quietly using the check_pattern
matched_df = df[
    df["review"].str.contains(check_pattern, case=False, na=False)
].copy()

# 4. Create the 3rd column by extracting the exact word that matched
matched_df["found_word"] = matched_df["review"].str.extract(
    extract_pattern, flags=re.IGNORECASE
)

# 5. Display the neat 3-column table
matched_df[["found_word", "review"]]

   found_word                                             review
12        btw  so im not a big fan of bolls work but then aga...

In [40]:
df["review"] = df["review"].apply(chat_conversion)

In [41]:
df["review"][12]

'so im not a big fan of bolls work but then again not many are i enjoyed his movie postal maybe im the only one boll apparently bought the rights to use far cry long ago even before the game itself was even finsished people who have enjoyed killing mercs and infiltrating secret research labs located on a tropical island should be warned that this is not far cry this is something mr boll have schemed together along with his legion of schmucks feeling loneley on the set mr boll invites three of his countrymen to play with these players go by the names of til schweiger udo kier and ralf moellerthree names that actually have made them selfs pretty big in the movie biz so the tale goes like this jack carver played by til schweiger yes carver is german all hail the bratwurst eating dudes however i find that tils acting in this movie is pretty badass people have complained about how hes not really staying true to the whole carver agenda but we only saw carver in a first person perspective so we dont really know what he looked like when he was kicking a however the storyline in this film is beyond demented we see the evil mad scientist dr krieger played by udo kier making geneticallymutatedsoldiers or gms as they are called performing his topsecret research on an island that reminds me of spoiler vancouver for some reason thats right no palm trees here instead we got some nice rich lumberjackwoods we havent even gone far before i started to cry mehehe i cannot go on any more if you wanna stay true to bolls shenanigans then go and see this movie you will not be disappointed it delivers the true boll experience meaning most of it will suckthere are some things worth mentioning that would imply that boll did a good work on some areas of the film such as some nice boat and fighting scenes until the whole cromedalbino gms squad enters the scene and everything just makes me laugh the movie far cry reeks of scheisse thats poop for you simpletons from a far if you wanna take a wiff go ahead By The Way carver gets a very annoying sidekick who makes you wanna shoot him the first three minutes hes on screen'

## Incorrect Text Handling Operations

In [42]:
from textblob import TextBlob

In [43]:
incorrect_text = 'ceertain conditionas duriing seveal ggenerations aree moodified in the saame maner.'

textBlb = TextBlob(incorrect_text)

textBlb.correct().string

'certain conditions during several generations are modified in the same manner.'

In [44]:
# Test on the first 10 rows
sample_df = df.head(10).copy()

In [45]:
# Apply TextBlob correction
sample_df["clean_review"] = sample_df["review"].apply(
    lambda text: str(TextBlob(text).correct())
)

# View the original and corrected text side-by-side
sample_df[["review", "clean_review"]]

,review,clean_review
0,one of the other reviewers has mentioned that ...,one of the other reviews has mentioned that af...
1,a wonderful little production the filming tech...,a wonderful little production the filling tech...
2,i thought this was a wonderful way to spend ti...,i thought this was a wonderful way to spend ti...
3,basically theres a family where a little boy j...,basically there a family where a little boy ja...
4,petter matteis love in the time of money is a ...,letter matters love in the time of money is a ...
5,probably my alltime favorite movie a story of ...,probably my alliee favorite movie a story of h...
6,i sure would like to see a resurrection of a u...,i sure would like to see a resurrection of a u...
7,this show was an amazing fresh innovative idea...,this show was an amazing fresh innovative idea...
8,encouraged by the positive comments about this...,encouraged by the positive comments about this...
9,if you like original gut wrenching laughter yo...,if you like original gut wrenching laughter yo...

## Stopwords Operations

In [46]:
from nltk.corpus import stopwords ## NLTK: Natural Level ToolKit library
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/prathamkumar/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [47]:
stopwords.words('english') ## Identify the language and pass here

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 'shouldn',
 "shouldn't",
 "should've",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 'were',
 'weren',
 "weren't",
 "we've",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 'your',
 "you're",
 'yours',
 'yourself',
 'yourselves',
 "you've"]

In [48]:
len(stopwords.words('english'))

198

In [49]:
def remove_stopwords(text):
    new_text = []

    for word in text.split():
        if word in stopwords.words('english'):
            new_text.append('')
        else:
            new_text.append(word)
    x = new_text[:]
    new_text.clear()
    return " ".join(x)

In [50]:
remove_stopwords('probably my all-time favorite movie, a story of selflessness, sacrifice and dedication to a noble cause, but it\'s not preachy or boring. it just never gets old, despite my having seen it some 15 or more times')

ERROR! Session/line number was not unique in database. History logging moved to new session 4

'probably  all-time favorite movie,  story  selflessness, sacrifice  dedication   noble cause,    preachy  boring.   never gets old, despite   seen   15   times'

In [51]:
df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production the filming tech...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically theres a family where a little boy j...  negative
4  petter matteis love in the time of money is a ...  positive

In [52]:
df['review'].apply(remove_stopwords)

0     one    reviewers  mentioned   watching  1 oz e...
1      wonderful little production  filming techniqu...
2      thought    wonderful way  spend time    hot s...
3     basically theres  family   little boy jake thi...
4     petter matteis love   time  money   visually s...
                            ...
95    daniel daylewis    versatile actor alive engli...
96     guess would    originally going    least two ...
97    well  like  watch bad horror bmovies cause  th...
98       worst movie   ever seen  well   worst    pr...
99        mario fan   long    remember    fond memor...
Name: review, Length: 100, dtype: str

## Remove Emoji Handle Operations

In [53]:
import re
def remove_emoji(text):
    emoji_pattern = re.compile("["
                           u"\U0001F600-\U0001F64F"  # emoticons
                           u"\U0001F300-\U0001F5FF"  # symbols & pictographs
                           u"\U0001F680-\U0001F6FF"  # transport & map symbols
                           u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
                           u"\U00002702-\U000027B0"
                           u"\U000024C2-\U0001F251"
                           "]+", flags=re.UNICODE)
    return emoji_pattern.sub(r'', text)

In [54]:
remove_emoji("Loved the movie. It was 😘😘")

'Loved the movie. It was '

In [55]:
remove_emoji("Lmao 😂😂")

'Lmao '

In [56]:
!pip install emoji

Requirement already satisfied: emoji in /Users/prathamkumar/.pyenv/versions/3.11.7/lib/python3.11/site-packages (2.15.0)

In [57]:
import emoji
print(emoji.demojize('Python is 🔥'))

Python is :fire:

In [58]:
print(emoji.demojize('Loved the movie. It was 😘'))

Loved the movie. It was :face_blowing_a_kiss:

## Tokenization Operations

### 1. Using the split function

In [59]:
# word tokenization
sent1 = 'I am going to delhi'
sent1.split()

['I', 'am', 'going', 'to', 'delhi']

In [60]:
# sentence tokenization
sent2 = 'I am going to delhi. I will stay there for 3 days. Let\'s hope the trip to be great'
sent2.split('.')

['I am going to delhi',
 ' I will stay there for 3 days',
 " Let's hope the trip to be great"]

In [61]:
# Problems with split function
sent3 = 'I am going to delhi!'
sent3.split()

['I', 'am', 'going', 'to', 'delhi!']

In [62]:
sent4 = 'Where do think I should go? I have 3 day holiday'
sent4.split('.')

['Where do think I should go? I have 3 day holiday']

### 2. Regular Expression

In [63]:
import re
sent3 = 'I am going to delhi!'
tokens = re.findall("[\w']+", sent3)
tokens

['I', 'am', 'going', 'to', 'delhi']

In [64]:

text = """Lorem Ipsum is simply dummy text of the printing and typesetting industry?
Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
when an unknown printer took a galley of type and scrambled it to make a type specimen book."""
sentences = re.compile('[.!?] ').split(text)
sentences

["Lorem Ipsum is simply dummy text of the printing and typesetting industry?\nLorem Ipsum has been the industry's standard dummy text ever since the 1500s,\nwhen an unknown printer took a galley of type and scrambled it to make a type specimen book."]

### 3. NLTK | Natural Language Toolkit

In [65]:
from nltk.tokenize import word_tokenize,sent_tokenize
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     /Users/prathamkumar/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [66]:
sent1 = 'I am going to visit delhi!'
word_tokenize(sent1)

['I', 'am', 'going', 'to', 'visit', 'delhi', '!']

In [67]:
text = """Lorem Ipsum is simply dummy text of the printing and typesetting industry?
Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
when an unknown printer took a galley of type and scrambled it to make a type specimen book."""

sent_tokenize(text)

['Lorem Ipsum is simply dummy text of the printing and typesetting industry?',
 "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,\nwhen an unknown printer took a galley of type and scrambled it to make a type specimen book."]

In [68]:
sent5 = 'I have a Ph.D in A.I'
sent6 = "We're here to help! mail us at nks@gmail.com"
sent7 = 'A 5km ride cost $10.50'

word_tokenize(sent5)

['I', 'have', 'a', 'Ph.D', 'in', 'A.I']

In [69]:
word_tokenize(sent6)

['We',
 "'re",
 'here',
 'to',
 'help',
 '!',
 'mail',
 'us',
 'at',
 'nks',
 '@',
 'gmail.com']

In [70]:
word_tokenize(sent7)

['A', '5km', 'ride', 'cost', '$', '10.50']

### 4. Spacy (good)

In [71]:
%pip uninstall -y spacy en-core-web-sm
%pip install -U spacy

Found existing installation: spacy 3.8.14
Uninstalling spacy-3.8.14:
  Successfully uninstalled spacy-3.8.14
Found existing installation: en_core_web_sm 3.8.0
Uninstalling en_core_web_sm-3.8.0:
  Successfully uninstalled en_core_web_sm-3.8.0
Note: you may need to restart the kernel to use updated packages.
Collecting spacy
  Using cached spacy-3.8.14-cp311-cp311-macosx_11_0_arm64.whl.metadata (28 kB)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /Users/prathamkumar/.pyenv/versions/3.11.7/lib/python3.11/site-packages (from spacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /Users/prathamkumar/.pyenv/versions/3.11.7/lib/python3.11/site-packages (from spacy) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /Users/prathamkumar/.pyenv/versions/3.11.7/lib/python3.11/site-packages (from spacy) (1.0.15)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /Users/prathamkumar/.pyenv/versions/3.11.7/lib/python3.11/site-packages (from spacy) (2.0.13)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /Users/prathamkumar/.pyenv/versions/3.11.7/lib/python3.11/site-packages (from spacy) (3.0.13)
Requirement already satisfied: thinc<8.4.0,>=8.3.12 in /Users/prathamkumar/.pyenv/versions/3.11.7/lib/python3.11/site-packages (from spacy) (8.3.13)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /Users/prathamkumar/.pyenv/versions/3.11.7/lib/python3.11/site-packages (from spacy) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.5.3 in /Users/prathamkumar/.pyenv/versions/3.11.7/lib/python3.11/site-packages (from spacy) (2.5.3)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /Users/prathamkumar/.pyenv/versions/3.11.7/lib/python3.11/site-packages (from spacy) (2.0.10)
Requirement already satisfied: weasel<2.0.0,>=1.0.0 in /Users/prathamkumar/.pyenv/versions/3.11.7/lib/python3.11/site-packages (from spacy) (1.0.0)
Requirement already satisfied: confection<2.0.0,>=1.3.2 in /Users/prathamkumar/.pyenv/versions/3.11.7/lib/python3.11/site-packages (from spacy) (1.3.3)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in /Users/prathamkumar/.pyenv/versions/3.11.7/lib/python3.11/site-packages (from spacy) (0.26.8)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /Users/prathamkumar/.pyenv/versions/3.11.7/lib/python3.11/site-packages (from spacy) (4.67.3)
Requirement already satisfied: numpy>=1.19.0 in /Users/prathamkumar/.pyenv/versions/3.11.7/lib/python3.11/site-packages (from spacy) (1.26.4)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /Users/prathamkumar/.pyenv/versions/3.11.7/lib/python3.11/site-packages (from spacy) (2.33.0)
Requirement already satisfied: pydantic<3.0.0,>=2.0.0 in /Users/prathamkumar/.pyenv/versions/3.11.7/lib/python3.11/site-packages (from spacy) (2.12.5)
Requirement already satisfied: jinja2 in /Users/prathamkumar/.pyenv/versions/3.11.7/lib/python3.11/site-packages (from spacy) (3.1.6)
Requirement already satisfied: setuptools in /Users/prathamkumar/.pyenv/versions/3.11.7/lib/python3.11/site-packages (from spacy) (65.5.0)
Requirement already satisfied: packaging>=20.0 in /Users/prathamkumar/.pyenv/versions/3.11.7/lib/python3.11/site-packages (from spacy) (26.2)
Requirement already satisfied: annotated-types>=0.6.0 in /Users/prathamkumar/.pyenv/versions/3.11.7/lib/python3.11/site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in /Users/prathamkumar/.pyenv/versions/3.11.7/lib/python3.11/site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (2.41.5)
Requirement already satisfied: typing-extensions>=4.14.1 in /Users/prathamkumar/.pyenv/versions/3.11.7/lib/python3.11/site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /Users/prathamkumar/.pyenv/versions/3.11.7/lib/python3.11/site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/prathamkumar/.pyenv/versions/3.11.7/lib/python3.11/site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /Users/prathamkumar/.pyenv/versions/3.11.7/lib/python3.11/site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.11)
Requirement already satisfied: urllib3<3,>=1.26 in /Users/prathamkumar/.pyenv/versions/3.11.7/lib/python3.11/site-packages (from requests<3.0.0,>=2.13.0->spacy) (2.6.3)
Requirement already satisfied: certifi>=2023.5.7 in /Users/prathamkumar/.pyenv/versions/3.11.7/lib/python3.11/site-packages (from requests<3.0.0,>=2.13.0->spacy) (2026.2.25)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in /Users/prathamkumar/.pyenv/versions/3.11.7/lib/python3.11/site-packages (from thinc<8.4.0,>=8.3.12->spacy) (1.3.3)
Requirement already satisfied: shellingham>=1.3.0 in /Users/prathamkumar/.pyenv/versions/3.11.7/lib/python3.11/site-packages (from typer<1.0.0,>=0.3.0->spacy) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /Users/prathamkumar/.pyenv/versions/3.11.7/lib/python3.11/site-packages (from typer<1.0.0,>=0.3.0->spacy) (15.0.0)
Requirement already satisfied: annotated-doc>=0.0.2 in /Users/prathamkumar/.pyenv/versions/3.11.7/lib/python3.11/site-packages (from typer<1.0.0,>=0.3.0->spacy) (0.0.4)
Requirement already satisfied: cloudpathlib>=0.7.0 in /Users/prathamkumar/.pyenv/versions/3.11.7/lib/python3.11/site-packages (from weasel<2.0.0,>=1.0.0->spacy) (0.24.0)
Requirement already satisfied: smart-open>=5.2.1 in /Users/prathamkumar/.pyenv/versions/3.11.7/lib/python3.11/site-packages (from weasel<2.0.0,>=1.0.0->spacy) (7.7.1)
Requirement already satisfied: httpx>=0.24.0 in /Users/prathamkumar/.pyenv/versions/3.11.7/lib/python3.11/site-packages (from weasel<2.0.0,>=1.0.0->spacy) (0.28.1)
Requirement already satisfied: anyio in /Users/prathamkumar/.pyenv/versions/3.11.7/lib/python3.11/site-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (4.13.0)
Requirement already satisfied: httpcore==1.* in /Users/prathamkumar/.pyenv/versions/3.11.7/lib/python3.11/site-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (1.0.9)
Requirement already satisfied: h11>=0.16 in /Users/prathamkumar/.pyenv/versions/3.11.7/lib/python3.11/site-packages (from httpcore==1.*->httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /Users/prathamkumar/.pyenv/versions/3.11.7/lib/python3.11/site-packages (from rich>=13.8.0->typer<1.0.0,>=0.3.0->spacy) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /Users/prathamkumar/.pyenv/versions/3.11.7/lib/python3.11/site-packages (from rich>=13.8.0->typer<1.0.0,>=0.3.0->spacy) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /Users/prathamkumar/.pyenv/versions/3.11.7/lib/python3.11/site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer<1.0.0,>=0.3.0->spacy) (0.1.2)
Requirement already satisfied: wrapt in /Users/prathamkumar/.pyenv/versions/3.11.7/lib/python3.11/site-packages (from smart-open>=5.2.1->weasel<2.0.0,>=1.0.0->spacy) (2.2.2)
Requirement already satisfied: MarkupSafe>=2.0 in /Users/prathamkumar/.pyenv/versions/3.11.7/lib/python3.11/site-packages (from jinja2->spacy) (3.0.3)
Using cached spacy-3.8.14-cp311-cp311-macosx_11_0_arm64.whl (6.4 MB)
Installing collected packages: spacy
Successfully installed spacy-3.8.14
Note: you may need to restart the kernel to use updated packages.

In [72]:
import sys
!{sys.executable} -m spacy download en_core_web_sm

Collecting en-core-web-sm==3.8.0
  Downloading en_core_web_sm-3.8.0-py3-none-any.whl (12.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 3.4 MB/s  0:00:03a 0:00:01m eta 0:00:01
Installing collected packages: en-core-web-sm
Successfully installed en-core-web-sm-3.8.0
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')

In [73]:
import spacy
nlp = spacy.load("en_core_web_sm")

In [74]:
doc = nlp("Hello, I am learning NLP.")
print([token.text for token in doc])

['Hello', ',', 'I', 'am', 'learning', 'NLP', '.']

In [75]:
doc1 = nlp(sent5)
doc2 = nlp(sent6)
doc3 = nlp(sent7)
doc4 = nlp(sent1)

In [76]:
doc4 = nlp(sent1)
doc4

I am going to visit delhi!

In [77]:
for token in doc4:
    print(token)

I
am
going
to
visit
delhi
!

In [78]:
df.head()

                                              review sentiment
0  one of the other reviewers has mentioned that ...  positive
1  a wonderful little production the filming tech...  positive
2  i thought this was a wonderful way to spend ti...  positive
3  basically theres a family where a little boy j...  negative
4  petter matteis love in the time of money is a ...  positive

# Stemmer

In [79]:
from nltk.stem.porter import PorterStemmer

In [80]:
ps = PorterStemmer()
def stem_words(text):
    return " ".join([ps.stem(word) for word in text.split()])

In [81]:
sample = "walk walks walking walked"
stem_words(sample)

'walk walk walk walk'

In [82]:
text = 'probably my alltime favorite movie a story of selflessness sacrifice and dedication to a noble cause but its not preachy or boring it just never gets old despite my having seen it some 15 or more times in the last 25 years paul lukas performance brings tears to my eyes and bette davis in one of her very few truly sympathetic roles is a delight the kids are as grandma says more like dressedup midgets than children but that only makes them more fun to watch and the mothers slow awakening to whats happening in the world and under her own roof is believable and startling if i had a dozen thumbs theyd all be up for this movie'
print(text)

probably my alltime favorite movie a story of selflessness sacrifice and dedication to a noble cause but its not preachy or boring it just never gets old despite my having seen it some 15 or more times in the last 25 years paul lukas performance brings tears to my eyes and bette davis in one of her very few truly sympathetic roles is a delight the kids are as grandma says more like dressedup midgets than children but that only makes them more fun to watch and the mothers slow awakening to whats happening in the world and under her own roof is believable and startling if i had a dozen thumbs theyd all be up for this movie

In [83]:
stem_words(text)

'probabl my alltim favorit movi a stori of selfless sacrific and dedic to a nobl caus but it not preachi or bore it just never get old despit my have seen it some 15 or more time in the last 25 year paul luka perform bring tear to my eye and bett davi in one of her veri few truli sympathet role is a delight the kid are as grandma say more like dressedup midget than children but that onli make them more fun to watch and the mother slow awaken to what happen in the world and under her own roof is believ and startl if i had a dozen thumb theyd all be up for thi movi'

# Lemmatization

In [84]:
import nltk
from nltk.stem import WordNetLemmatizer
import nltk
nltk.download('wordnet')
nltk.download('omw-1.4')
wordnet_lemmatizer = WordNetLemmatizer()

sentence = "He was running and eating at same time. He has bad habit of swimming after playing long hours in the Sun."
punctuations="?:!.,;"
sentence_words = nltk.word_tokenize(sentence)
for word in sentence_words:
    if word in punctuations:
        sentence_words.remove(word)

sentence_words
print("{0:20}{1:20}".format("Word","Lemma"))
for word in sentence_words:
    print ("{0:20}{1:20}".format(word,wordnet_lemmatizer.lemmatize(word,pos='v')))

[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/prathamkumar/nltk_data...

Word                Lemma

[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     /Users/prathamkumar/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

He                  He
was                 be
running             run
and                 and
eating              eat
at                  at
same                same
time                time
He                  He
has                 have
bad                 bad
habit               habit
of                  of
swimming            swim
after               after
playing             play
long                long
hours               hours
in                  in
the                 the
Sun                 Sun

#### NOTE: Stemming & lamatization are same to retrieve root words but lamatization is worked good. Lamatization is slow & stemming is fast

In [85]:
import os

data_path = "content/IMDB Dataset.csv"

if os.path.exists(data_path):
    os.remove(data_path)
    print("File deleted successfully")
else:
    print("File not found")

File deleted successfully